### ISSUE TITLE
codec streaming encode question

### ISSUE THREAD

**Issue by qinguoan** [ugorji/go#161] opened 2016-06-13 16:20 UTC
Hi ,

I used this package with net/http.
func(w http.ResponseWriter, r *http.Request) {
                obj := &SomeStruct{......}
		flusher := w.(http.Flusher)
                ... ...
                for {
                       select{
                       case obj:=<- someChan:
                               codec.NewEncoder(w,new(codec.JsonHandle)).Encode(obj)
                               flusher.Flush()    
                       ... ...
                       }                        
                }
}
Above doesn't work as expected, if I use encoding/json and json.NewEncoder(w).Encode(obj) instead, it works well. Is it a problem?

**Comment by ugorji** [comment] 2016-08-08 21:52
I don't know what the problem is. You need to spell out your problem description precisely, so I can investigate and fix.

Please do the following:
- provide a reproducer (e.g. a test go file that i can run with go test, or a main file that I can run with go run
- tell me what the expected output is, and what you get
- I can then run your reproducer, verify what you state, and provide a quick fix.

Thanks.

**Comment by ugorji** [comment] 2016-08-25 15:54
ping. If no response, I will close. Thanks.

**Comment by ugorji** [comment] 2016-08-29 14:44
I think there's a UserError here. Nothing shows that there is a bug here, and there no reproducer on your part to show that there is. Closing now.

**Closed by ugorji** 2016-08-29 14:44 UTC
Labels: NeedMoreInfo, UserError
