### ISSUE TITLE
Compatibility with `encoding/json`

### ISSUE THREAD

**Issue by junchih** [ugorji/go#328] opened 2020-02-12 02:26 UTC
hi guys,

will this library be compatible with the official golang json library `encoding/json`? I just noticed that we've defined a `Raw` data type https://github.com/ugorji/go/blob/master/codec/helper.go#L1063. which will cause the modification of caller's data structure to use this library. is that ok?

**Comment by ugorji** [comment] 2020-09-08 23:11
codec is not 100% compatible with encoding/json, by design. There are some areas that we decided that a different way of resolving will be better. However, these are on the edges. For most uses, there is great compatibility.

**Closed by ugorji** 2020-09-08 23:11 UTC
