### ISSUE TITLE
With CBOR, time values not equal  after encoding & decoding. 

### ISSUE THREAD

**Issue by ghts** [ugorji/go#239] opened 2018-04-03 10:12 UTC
[TestCborTimeIssue.go.txt](https://github.com/ugorji/go/files/1871090/TestCborTimeIssue.go.txt)

This simple test case check the correctness of  'encoding & decoding' of time value in CBOR.

(For the source code, please refer to the attachment.)

A random time value is 'encoded & decoded' and compared with original value.

Expected  2 time values are equal, but, test result shows that it is not the case.

Test Environment:
- Windows 10 64bit 
- Go 1.10.1 64bit

I ran "go test github.com/ugorji/go/codec -run ^TestCborTimeIssue$"

```
package codec

import (
	"bytes"
	"fmt"
	"math/rand"
	"testing"
	"time"
)

func TestCborTimeIssue(t *testing.T) {
	cborHandle := new(CborHandle)
	buffer := new(bytes.Buffer)

	var tt, tt2 time.Time

        // randome seed
	r := rand.New(rand.NewSource(time.Now().UnixNano() + rand.Int63()))

	// random time value
	tt = time.Date(r.Intn(200)+1970, time.Month(r.Intn(12)), r.Intn(31),
		r.Intn(24), r.Intn(60), r.Intn(60), r.Intn(1000000000), time.Now().Location())

	// encoding
	if err := NewEncoder(buffer, cborHandle).Encode(tt); err != nil {
		println(err.Error())
		t.Fail()
	}

	// decoding
	if err := NewDecoderBytes(buffer.Bytes(), cborHandle).Decode(&tt2); err != nil {
		println(err.Error())
		t.Fail()
	}

	// compare with original value
	if !tt.Equal(tt2) {
		fmt.Printf("time : values not equal\n1: %v\n2: %v\ndifference: %v\n", tt2, tt, tt2.Sub(tt))
		t.Fail()
	}
}
```

and received output below

```
time : values not equal
1: 2012-11-16 15:25:32.417818 +0000 UTC
2: 2012-11-17 00:25:32.417817656 +0900 KST
difference: 344ns
FAIL	github.com/ugorji/go/codec	0.653s
```

but expected output below.

```
ok  	github.com/ugorji/go/codec	1.231s
```

**Comment by ghts** [comment] 2018-04-05 11:27
In cbor.go, when 2 functions (EncodeTime & decodeTime) are modified as below, the test case passes.

All the commented & deactivated codes are the original ones.

Pro : It works. (For now)
Con : Its time value is limited quite narrow scope (1678~2262).

```
func (e *cborEncDriver) EncodeTime(t time.Time) {
	if t.IsZero() {
		e.EncodeNil()
	} else if e.h.TimeRFC3339 {
		e.encUint(0, cborBaseTag)
		e.EncodeString(cUTF8, t.Format(time.RFC3339Nano))
	} else {
		e.encUint(1, cborBaseTag)

		// For simplicity, usse nanosecond value only.   Added. 
		e.EncodeUint(uint64(t.UTC().UnixNano()))   // Added.

		//t = t.UTC().Round(time.Microsecond)
		//sec, nsec := t.Unix(), uint64(t.Nanosecond())
		//if nsec == 0 {
		//	e.EncodeInt(sec)
		//} else {
		//	e.EncodeFloat64(float64(sec) + float64(nsec)/1e9)
		//}
	}
}

func (d *cborDecDriver) decodeTime(xtag uint64) (t time.Time) {
	if !d.bdRead {
		d.readNextBd()
	}
	switch xtag {
	case 0:
		var err error
		if t, err = time.Parse(time.RFC3339, stringView(d.DecodeStringAsBytes())); err != nil {
			d.d.errorv(err)
		}
	case 1:
		// For simplicity, usse nanosecond value only. Added.
		t = time.Unix(0, d.DecodeInt64()).Local()   // Added.

		// decode an int64 or a float, and infer time.Time from there.
		// for floats, round to microseconds, as that is what is guaranteed to fit well.
		//switch {
		//case d.bd == cborBdFloat16, d.bd == cborBdFloat32:
		//	f1, f2 := math.Modf(d.DecodeFloat64())
		//	t = time.Unix(int64(f1), int64(f2*1e9))
		//case d.bd == cborBdFloat64:
		//	f1, f2 := math.Modf(d.DecodeFloat64())
		//	t = time.Unix(int64(f1), int64(f2*1e9))
		//case d.bd >= cborBaseUint && d.bd < cborBaseNegInt,
		//	d.bd >= cborBaseNegInt && d.bd < cborBaseBytes:
		//	t = time.Unix(d.DecodeInt64(), 0)
		//default:
		//	d.d.errorf("time.Time can only be decoded from a number (or RFC3339 string)")
		//}
	default:
		d.d.errorf("invalid tag for time.Time - expecting 0 or 1, got 0x%x", xtag)
	}

	//t = t.UTC().Round(time.Microsecond)

	return
}
```

**Comment by ugorji** [comment] 2018-04-06 15:37
cbor spec defines 2 modes of encoding time:
- seconds since epoch
- RFC3339 format
(see https://tools.ietf.org/html/rfc7049#section-2.4.1)

By default, seconds since epoch is used. CborHandle allows you switch to RFC3339 format using the flag: TimeRFC3339=true (see https://godoc.org/github.com/ugorji/go/codec#CborHandle).

Because you inadvertently used the former model (seconds since epoch), all milliseconds etc are ignored, or a float is used which is guaranteed to not be exact. Thus the discrepancy in equals.

This is a limitation of cbor format leveraging floats, and the inability to exactly represent large fractional floats in computing. 

To have a better calculation, use exact milliseconds (not nanoseconds) and compare using UTC on both sides, or use RFC 3339 format.

Closing this.

**Closed by ugorji** 2018-04-06 15:37 UTC
Labels: UserError

**Comment by ugorji** [comment] 2018-04-06 15:39
P.S. Please update if you use exact milliseconds (or 0 milliseconds) and UTC on both sides and still get a difference. I have tests that exact this code, and worked hard to get it to some semblance of correctness. So would want to ensure that this works as designed. 

Please explicitly tag me (ie use @ugorji in your response) if you still see an issue, so I can re-check.

**Comment by ghts** [comment] 2018-04-09 05:07
@ugorji 

> This is a limitation of cbor format.

When I looked the cbor code, I could not understand why using Float type for time.

Now, I am clear that it is limitation of CBOR format.

Based on your detailed explanation, 

I chose to use (updated) MessagePack format, (rather than CBOR format).


Thank you for generous & detailed reply.

Cheers.~
