### ISSUE TITLE
can no longer decode into type with nil interface

### ISSUE THREAD

**Issue by BurntSushi** [ugorji/go#212] opened 2017-10-23 13:35 UTC
Running `go test` on this program fails on [current master](https://github.com/ugorji/go/commit/a9859e30962a3ede5e5677997480a04d063fec6d):

```go
package main

import (
	"bytes"
	"encoding/json"
	"testing"

	"github.com/ugorji/go/codec"
)

type Foo interface {
	AMethod()
}

type AFoo struct {
	Field string `json:"field"`
}

func (x AFoo) AMethod() {}

type Data struct {
	Foo Foo
}

func (d *Data) UnmarshalJSON(rawdata []byte) error {
	var afoo AFoo
	if err := json.Unmarshal(rawdata, &afoo); err != nil {
		return err
	}
	*d = Data{Foo: afoo}
	return nil
}

func TestWat(t *testing.T) {
	raw := `{"Foo": {"field": "field contents"}}`
	handle := &codec.JsonHandle{}
	rdr := bytes.NewReader([]byte(raw))
	decoder := codec.NewDecoder(rdr, handle)

	var data Data
	err := decoder.Decode(&data)
	if err != nil {
		t.Fatalf("error decoding: %s", err)
	}
}
```

The failure is:

```
go test
--- FAIL: TestWat (0.00s)
        bug_test.go:43: error decoding: [pos 9]: cannot decode non-nil codec value into nil main.Foo (1 methods)
FAIL
exit status 1
FAIL    bug     0.003s
```

Running this test against `ugorji/go` on commit 5efa3251c7f7d05e5d9704a69a984ec9f1386a40 succeeds.

**Comment by ugorji** [comment] 2017-10-23 14:28
Add a MarshalJSON method to *Data, and try it again.

If that works, then it works as designed. The library expects that you will have MarshalJSON and UnmarshalJSON in concert on a given type. 

Let me know before I dig in further.

**Comment by ugorji** [comment] 2017-10-23 14:55
I tested this, and it works fine if you have an accompanying MarshalJSON() ([]byte, error) method.

Closing this as "works as designed".

In our view, if you define an UnmarshalJSON, then you should define an accompanying MarshalJSON for symmetry.

**Closed by ugorji** 2017-10-23 14:55 UTC
Labels: UserError, WorkAsDesigned

**Comment by BurntSushi** [comment] 2017-10-23 15:29
Is that documented anywhere?

**Comment by ugorji** [comment] 2017-10-23 16:23
Not documented - but I thought expected i.e. if you define a custom way to encode, then you MUST have defined a corresponding custom way to encode. 

If you disagree with above, please explain your alternate position, so I can understand and course-correct if needed.

I can document it on the documentation site.

**Comment by BurntSushi** [comment] 2017-10-23 17:10
I don't think your position is terribly unreasonable, but I certainly don't find it obvious. There's no way I could have known *that* was my problem given the sample program I provided and the error reported by the library. For all I know, it's just a bug in how your unmarshaling code is written. Moreover, the standard `encoding/json` package doesn't have this restriction, so it's not like it's standard behavior among reflection based encoding implementation either.

The specific use case *for the code in my initial comment* is when you want to deserialize a JSON blob into an interface that represents one of several concrete types based on other parts of the payload. e.g., an AST. Here's one way of doing just that:

```
type AST interface {
    Children() []AST
}

type Expr struct {}
func (a Expr) Children() []AST { ... }

type Statement struct {}
func (a Statement) Children() []AST { ... }

type Parsed struct {
    // The type of the AST node represented, e.g., `Expr` or `Statement`
    Type string `json:"type"`
    // The AST node itself.
    Node AST
}

func (p *Parsed) UnmarshalJSON(raw []byte) error {
    var data struct {
        Type string `json:"type"`
        Node json.RawMessage `json:"data"`
    }
    if err := json.Unmarshal(raw, &data); err != nil {
        return err
    }
    var ast AST
    switch data.Type {
    case "Expr":
        var a Expr
        if err := json.Unmarshal(data.Node, &a); err != nil {
            return err
        }
        ast = a
    case "Statement":
        var a Statement
        if err := json.Unmarshal(data.Node, &a); err != nil {
            return err
        }
        ast = a
    default:
        return fmt.Errorf("unrecognized AST type: %s", data.Type)
    }
    *p.Type = data.Type
    *p.Node = ast
    return nil
}
```

Notice that there is no need to write a corresponding `MarshalJSON` method for `Parsed` because it will serialize correctly using automatic marshaling.

With that said, requiring the definition of a `MarshalJSON` method isn't terribly onerous. It's just not at all clear that *that* is what would solve my problem. So that's why I asked if it was documented anywhere.

**Comment by BurntSushi** [comment] 2017-10-23 17:13
Thank you for the work around though. That does indeed solve both my minimal example and the original source of the problem (which looks a lot like the `AST` example above).

**Comment by ugorji** [comment] 2017-10-24 07:31
Thanks much for your detailed explanation. Much appreciated. I spent some time thinking through this again, to see what my options are. There aren't any better options that documenting this. Let me explain below.

I definitely see the use-case for this, especially when you need to decode into non-empty interfaces. In this scenario, the default encoding is fine (as the interface value is either nil or a value of the implementation, meaning you either encode as nil or as a real value). It is only during decoding that there is a problem, as the engine cannot infer what implementation class to use.

I am still not comfortable relaxing the requirement, because codec affords a long list of symetric ways of handling encode/decode:
- is the type a codec.Selfer (codec's performant interface with access to Encoder/Decoder)?
- is the type an extension, and we use a pair of encode/decode extension
- is the format binary-based and the type a encoding,Binary(M|Unm)arshaler, and we use the BinaryMarshal/BinaryUnmarshal methods
- is the format text-based and the type an encoding.Text(M|Unm)arshaler
- is the format json and the type an encoding/json.(M|Unm)arshaler
- else we find corresponding pairs of methods to handle both sides based on kind (slice, map, int, etc)

Due to this symmetry, we reduce the chances of issues happening e.g. encoding being done via encoding.TextMarshal while decoding is done via encoding/json.Unmarshal or based on the kind, and then encoding and decoding are out of sync.

The next question is about error handling. Since codec only reports on errors, it is not an error that you have only one part of the symetry. At best, it will be a warning, but we can't surface warnings. In your use-case, the code then tried to decode into a non-empty interface, and that failed. i.e. it didn't pass any of the earlier checks where a user can define how to encode/decode themselves, so the engine tried to do it the generic way, and barfed when it saw a non-empty interface and no clues on how to decode it. In your example, you specify (via UnmarshalJSON) that you instantiate the interface based on the "type" field or otherwise.

I will document this in the docs of the library, so this is clear that we depend on the symetry, and ignore if only one side of the symetry is defined.

Hope this gives some idea into the thinking.

**Comment by BurntSushi** [comment] 2017-10-24 11:13
@ugorji Sounds good, thanks! I think clearer documentation is a fine solution!

**Comment by ugorji** [comment] 2017-10-24 11:23
Looking to add the text below to the overall documentation of the package (top-level). Wanted to get your thoughts first, in case I can make it clearer. Thoughts?

----

Custom Encoding and Decoding

This package maintains symmetry in the encoding and decoding halfs.
We determine how to encode or decode by walking this decision tree

  - is type a codec.Selfer?
  - is there an extension registered for the type?
  - is format binary, and is type a encoding.BinaryMarshaler and BinaryUnmarshaler?
  - is format specifically json, and is type a encoding/json.Marshaler and Unmarshaler?
  - is format text-based, and type an encoding.TextMarshaler?
  - else we use a pair of functions based on the "kind" of the type e.g. map, slice, int64, etc

This symmetry is important to reduce chances of issues happening because the
encoding and decoding sides are out of sync e.g. decoded via very specific
encoding.TextUnmarshaler but encoded via kind-specific generalized mode.

Consequently, if a type only defines one-half of the symetry
(e.g. it implements UnmarshalJSON() but not MarshalJSON() ),
then that type doesn't satisfy the check and we will continue walking down the
decision tree.

**Comment by BurntSushi** [comment] 2017-10-24 11:27
@ugorji Yeah that sounds great! I think that would have cleared up my initial problem.
