### ISSUE TITLE
Go vet warnings

### ISSUE THREAD

**Issue by mrz1836** [ugorji/go#183] opened 2016-12-23 13:55 UTC
`vendor/github.com/ugorji/go/codec/gen-helper.generated.go:1: possible malformed +build comment
vendor/github.com/ugorji/go/codec/simple.go:343: unrecognized printf verb ' '
exit status 1`

**Comment by ugorji** [comment] 2017-01-06 20:25
The first one is not a bug, and cannot be solved, as we want a way to comment this out. I think the vet tool should be changed to not flag this.

The second one is a bug, and I have now fixed (but not uploaded upstream yet)

**Comment by ugorji** [comment] 2017-01-07 11:50
K - I can change it to /*  */ to prevent "vet" from flagging as a potential issue.

Fix coming soon.

**Comment by ugorji** [comment] 2017-01-07 11:58
Fixed with 2 changes above

**Closed by ugorji** 2017-01-07 11:58 UTC
