### ISSUE TITLE
json unmarshal has error on mac plain

### ISSUE THREAD

**Issue by leonardyp** [ugorji/go#184] opened 2017-01-06 06:34 UTC
parsing time "2017-01-04T07:49:25.975545407Z"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "2017-01-04T07:49:25.975545407Z"" as """

go version go1.6.2 darwin/amd64
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/leonard/gopath:/Users/leonard/study"
GORACE=""
GOROOT="/Users/leonard/software/go/go1.6.2"
GOTOOLDIR="/Users/leonard/software/go/go1.6.2/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1" 
```
mac pro OS X Yosemite 10.10.5

**Comment by ugorji** [comment] 2017-01-06 20:14
I have no idea what to do with this. 

Can you please file a bug report if there is a bug.

It should include a reproducer that I can run using go run main.go or go test.

Also include and contrast what you get vs what you expected to get.

**Comment by ugorji** [comment] 2017-01-07 11:52
Closing this, as it's not a bug report.

Please respond with an easy-to-run reproducer and details on what you expect when executing reproducer vs what you get, and I will re-open.

**Closed by ugorji** 2017-01-07 11:52 UTC
Labels: NeedMoreInfo
